version: 0.2
phases:
  pre_build:
    commands:
    - echo "Entered the pre-build phase"
    - mvn test
  build:
    commands:
    - echo "Entered build phase"
    - mvn clean prepare-package war:exploded
    - mvn package
  post_build:
    commands:
    - echo "Entered the post-build phase"
    - mv target/jaikisan-demo-0.0.1-SNAPSHOT ./
    - mv target/jaikisan-demo-0.0.1-SNAPSHOT.war
artifacts:
  files:
    - jaikisan-demo-0.0.1-SNAPSHOT/**/*
    - jaikisan-demo-0.0.1-SNAPSHOT.war